export const tema = {
  primary: "#100F0F",
  secondary: "#FFFCF0",
  background1: "#ffffff",
  border1: "1px solid #100F0F1A",
  grid: 8,
  baseUnitHalf: "5px",
  baseUnit: "10px",
  baseUnit2: "20px",
  baseUnit4: "40px",
  baseUnit8: "80px",
  baseUnit12: "120px",
  font: {
    fontFamily: "'Quador', Georgia, Times New Roman, serif",
    size: {
      small: "15px",
      medium: "20px",
      large: "30px",
      xLarge: "40px",
      xxLarge: "60px",
    },
  },
  minBreakPoints: {
    small: "451px",
    medium: "769px",
    large: "961px",
    xlarge: "1281px",
  },
  maxBreakPoints: {
    small: "450px",
    medium: "768px",
    large: "960px",
    xLarge: "1280px",
  },
};
